# Generated by Django 4.0.4 on 2022-05-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_product_pvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='user_updated',
        ),
    ]
