# Generated by Django 4.0.4 on 2022-05-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='existencia',
        ),
    ]
