# Generated by Django 4.0.4 on 2022-05-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
